Der Thermini sendet keine NoteOn/NoteOff Werte sondern Control/Mode Change (176 dez.) auf Channel 1.
Dabei ist der Wert 2 für Volume und 20 für Pitch.
Der Wertebereich geht von 0 - 127.

.Pitch
+++[176, 20, 60] => Chan 1 / Control/Mode change / Pitch / 60+++
+++[176, 20, 63] => Chan 1 / Control/Mode change / Pitch / 63+++
+++[176, 20, 65] => Chan 1 / Control/Mode change / Pitch / 65+++
+++[176, 20, 68] => Chan 1 / Control/Mode change / Pitch / 68+++

.Volume
+++[176, 2, 125] => Chan 1 / Control/Mode change / Volume / 125+++
+++[176, 2, 60] => Chan 1 / Control/Mode change / Volume / 60+++

. Der MIDI CallbackHandler bekommt eine MIDI Message
. Ist es NoteOn/NoteOff oder Control Change?

.. NoteOn/NoteOff

.. Control Change
... Ist es Volume (2) oder Pitch (20)?

.... Volume

  Der Wert in der Variable param.currentVolume gespeichert
  
.... Pitch

  Der Wert wird an die Methode _send_ übergeben
  
== Send(value)

. map value to defined ranges (param)

  Damit bekomme ich einen Wert zwischen 0 und 360.

. Umrechnen des Werts in RGB  

== Datentypen

Wenn ein Byte Array verwendet werden muss, kann ein Tuple wie folgt umgewandelt werden:

    def dmxData(self, data: tuple):
        newData = [0]*512
        for i in range(0, min(len(data), 512)):
          newData[i] = data[i]

Diese Funktion stamm aus https://github.com/Hundemeier/sacn/blob/master/sacn/messages/data_packet.py[DataPacket].

== Examples

=== StupidArtnet

Quelle:: https://github.com/verycollective/stupidArtnet

Beispiel stupidArtnet-example.py funktioniert.

Kann mit 'The ArtNetominator' auf Windows gemonitored werden:

Port: 6454

Adapter: 192.168.56.1

Net: 0

Universe: 1

Datentypen:

a.set_single_value(1, 255)			# set channel 1 to 255

packet = bytearray(packet_size)		# create packet for Artnet

	for i in range(packet_size):  	# Fill buffer with random stuff
		packet[i] = random.randint(0, 255)

Beispiel stupid-midi2dmx.py muss noch komplettiert werden.

NOTE:: Basic aber funktioniert

=== pyartnet

Quelle:: https://github.com/spacemanspiff2007/PyArtNet

pyartnet is a python implementation of the ArtNet protocol using asyncio.
Usage

    node = ArtNetNode('IP')
    node.start()

    universe = node.add_universe(0)
    channel  = universe.add_channel(129,3)

    channel.add_fade([255,0,0], 5000)

NOTE::Zu wenig Dokumentation

=== py-art-net

Quelle:: https://github.com/ozel/py-artnet

Python art net interface. with patterns you can run for the ledpoles and the ledmatrix fridgefire made.

or anything that has a network based artnet interface.

I made it easier to config and run patterns with python code.
Dependencies.

NOTE::python2.7 source

=== sacn

Quelle:: https://github.com/Hundemeier/sacn

Sieht vielversprechend aus.

sacn-example.py muss noch getestet werden.

NOTE::Benötigt Python 3.6